x-uv: &pyuv
  restart: unless-stopped
  build:
    context: "."
    dockerfile: Dockerfile.pyuv

x-standard: &standard
  image: python:3.11
  restart: unless-stopped
  depends_on:
    hs_postgresql:
      condition: service_started

x-httpservercommand: &httpservercommand
  command: python -m http.server 8000

x-body: &body
  ports:
    - 8000:8000
    - 8001:8001 # debug ports
    - 8002:8002 # debug ports
  volumes:
    - ./stack/hydroserver-api-services:/app
    - staticfiles:/app/staticfiles
    - mediafiles:/app/mediafiles
    - pypackages:/usr/local/lib/python3.11/site-packages
  working_dir: /app
  environment:
    DEFAULT_SUPERUSER_EMAIL: "mail@groupeffect.de"
    DEFAULT_SUPERUSER_PASSWORD: "pass"
    SERVER_ENVIRONMENT: "Development"
    DATABASE_URL: "postgresql://admin:pass@hs_postgresql:5432/hydroserver"  # A connection to the PostgreSQL or TimescaleDB server HydroServer will use.
    ALLOWED_HOSTS: "*"              # Defaults to the host of PROXY_BASE_URL.

x-preparecommand: &preparecommand
  command: pip install -r requirements.txt

x-standardcommand: &standardcommand
  command:
    - sh
    - -c
    - |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py load_etl_test_data
      python manage.py load_sta_test_data
      python manage.py load_sta_test_observations 10
      python manage.py collectstatic --noinput
      python manage.py runserver 0.0.0.0:8000

x-debugcommand: &debugcommand
  command:
    - sh
    - -c
    - |
      source .venv/bin/activate
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py configure_timescaledb
      python manage.py collectstatic --noinput
      # python manage.py runserver 0.0.0.0:8000
      # python -m http.server 8000
      python -m debugpy --listen 0.0.0.0:8001 --wait-for-client manage.py runserver 0.0.0.0:8000

x-uvdebugcommand: &uvdebugcommand
  command:
    - sh
    - -c
    - |
      cd /
      uv init app
      uv python install 3.11
      uv python pin 3.11
      uv add debugpy
      cd /app 
      uv add -r requirements.txt
      uv python pin 3.11
      python -m http.server 8002
      # uv run manage.py makemigrations
      # uv run manage.py migrate
      # uv run manage.py load_etl_test_data
      # uv run manage.py load_sta_test_data
      # uv run manage.py load_sta_test_observations 10
      # uv run manage.py collectstatic --noinput
      # uv run -m debugpy --listen 0.0.0.0:8001 --wait-for-client manage.py runserver 0.0.0.0:8000

x-uvruncommand: &uvruncommand
  command:
    - sh
    - -c
    - |
      cd /
      uv init app
      uv python install 3.11
      uv python pin 3.11
      cd /app 
      uv add -r requirements.txt
      uv run manage.py makemigrations
      uv run manage.py migrate
      # uv run manage.py load_etl_test_data
      # uv run manage.py load_sta_test_data
      uv run manage.py load_sta_test_observations 10
      uv run manage.py collectstatic --noinput
      uv run manage.py runserver 0.0.0.0:8000

services:
  hs_postgresql:
    restart: unless-stopped
    image: docker.io/postgres:17
    container_name: hs_postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hydroserver
    ports:
      - "5432:5432"
    volumes:
      - hydroserver_dev_data:/var/lib/postgresql/data

  # hs_prepare_django:
  #   container_name: hs_prepare_django
  #   <<: *standard
  #   <<: *body
  #   <<: *preparecommand
  #   # <<: *httpservercommand

  hs_django:
    container_name: hs_django
    <<: 
    - *standard
    - *body
    - *standardcommand
    restart: unless-stopped
    depends_on:
      hs_postgresql:
        condition: service_started

  hs_nodejs:
    environment:
      VITE_APP_PROXY_BASE_URL: "" # must be set to empty string
    restart: unless-stopped
    container_name: hs_nodejs
    image: node:latest
    working_dir: /app
    ports:
      - 5173:5173
    volumes:
      - ./stack/hydroserver-data-management-app:/app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run docker-dev

  hs_nginx:
    restart: unless-stopped
    container_name: hs_nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/staticfiles
      - mediafiles:/mediafiles
    ports:
      - "8080:8080"
    depends_on:
      hs_django: 
        condition: service_started
      hs_nodejs: 
        condition: service_started
volumes:
  hydroserver_dev_data:
  staticfiles:
  mediafiles:
  pypackages: