FROM docker.io/python:3.11 as coreimage
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN apt update && apt -y dist-upgrade
RUN apt install -y jq
FROM coreimage
WORKDIR /
RUN uv init app
