x-uv: &pyuv
  restart: unless-stopped
  build:
    context: "."
    dockerfile: Dockerfile.pyuv

x-standard: &standard
  restart: unless-stopped
  image: python:3.11

x-standardcommand: &standardcommand
  command:
    - sh
    - -c
    - |
      python -m venv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py load_etl_test_data
      python manage.py load_sta_test_data
      python manage.py load_sta_test_observations 10
      python manage.py collectstatic --noinput
      python manage.py runserver 0.0.0.0:8000

x-debugcommand: &debugcommand
  command:
    - sh
    - -c
    - |
      source .venv/bin/activate
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py configure_timescaledb
      python manage.py collectstatic --noinput
      # python manage.py runserver 0.0.0.0:8000
      # python -m http.server 8000
      python -m debugpy --listen 0.0.0.0:8001 --wait-for-client manage.py runserver 0.0.0.0:8000

x-uvdebugcommand: &uvdebugcommand
  command:
    - sh
    - -c
    - |
      cd /
      uv init app
      uv python install 3.11
      uv python pin 3.11
      uv add debugpy
      cd /app 
      uv add -r requirements.txt
      uv python pin 3.11
      python -m http.server 8002
      # uv run manage.py makemigrations
      # uv run manage.py migrate
      # uv run manage.py load_etl_test_data
      # uv run manage.py load_sta_test_data
      # uv run manage.py load_sta_test_observations 10
      # uv run manage.py collectstatic --noinput
      # uv run -m debugpy --listen 0.0.0.0:8001 --wait-for-client manage.py runserver 0.0.0.0:8000

x-uvruncommand: &uvruncommand
  command:
    - sh
    - -c
    - |
      cd /
      uv init app
      uv python install 3.11
      uv python pin 3.11
      cd /app 
      uv add -r requirements.txt
      uv run manage.py makemigrations
      uv run manage.py migrate
      # uv run manage.py load_etl_test_data
      # uv run manage.py load_sta_test_data
      uv run manage.py load_sta_test_observations 10
      uv run manage.py collectstatic --noinput
      uv run manage.py runserver 0.0.0.0:8000

services:
  hs_postgresql:
    restart: unless-stopped
    image: docker.io/postgres:17
    container_name: hs_postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hydroserver
    ports:
      - "5432:5432"
    volumes:
      - hydroserver_dev_data:/var/lib/postgresql/data

  hs_django:
    <<: *standard
    <<: *standardcommand
    container_name: hs_django
    restart: unless-stopped
    ports:
      - 8000:8000
      - 8001:8001 # debug ports
      - 8002:8002 # debug ports
    volumes:
      - ./stack/hydroserver-api-services:/app
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    working_dir: /app
    environment:
      DEFAULT_SUPERUSER_EMAIL: "mail@groupeffect.de"
      DEFAULT_SUPERUSER_PASSWORD: "pass"
      SERVER_ENVIRONMENT: "Development"
      DATABASE_URL: "postgresql://admin:pass@hs_postgresql:5432/hydroserver"  # A connection to the PostgreSQL or TimescaleDB server HydroServer will use.
      ALLOWED_HOSTS: "*"              # Defaults to the host of PROXY_BASE_URL.
      # Deployment Settings
      # PROXY_BASE_URL: ""             # The base URL HydroServer will be served from.
      # DEBUG: ""                      # True/False: This should be set to False in production environments.
      # DEPLOYMENT_BACKEND: ""         # Use 'aws' or 'gcp' for cloud deployments, otherwise use 'local'.
      # SECRET_KEY: ""                 # This is required by Django. Keep this value secret.
      # DEFAULT_SUPERUSER_EMAIL: ""    # The email of the admin user created during initial startup.
      # DEFAULT_SUPERUSER_PASSWORD: "" # The password of the admin user created during initial startup.
      # ENABLE_AUDITS: ""              # True/False: This will track user activity in the sta app.
      # # Account Settings
      # SMTP_URL: ""                  # A connection to the SMTP server Django will send account related emails from.
      # DEFAULT_FROM_EMAIL: ""        # The email address Django will send account related emails from.
      # ACCOUNT_SIGNUP_ENABLED: ""    # True/False: Controls whether new users can create their own accounts.
      # ACCOUNT_OWNERSHIP_ENABLED: "" # True/False: Controls whether new users can create/own workspaces.
      # SOCIALACCOUNT_SIGNUP_ONLY: "" # True/False: Controls whether non-social account creation is supported.
      # # Database Settings
      # CONN_MAX_AGE: ""       # Controls how long Django will hold database connections open before closing them.
      # CONN_HEALTH_CHECKS: "" # True/False: Controls whether connection health checks are enabled.
      # SSL_REQUIRED: ""       # True/False: Controls whether Django will connect to the database using SSL.
      # # Storage Settings
      # MEDIA_BUCKET_NAME: ""     # The name of the AWS or GCP bucket photos will be stored in.
      # STATIC_BUCKET_NAME: ""    # The name of the AWS or GCP bucket static files will be stored in.
      # APP_CLIENT_URL: ""        # The base URL media and static files will be served from, if not the PROXY_BASE_URL.
      # AWS_CLOUDFRONT_KEY: ""    # The AWS CloudFront key used to generate signed photo URLs.
      # AWS_CLOUDFRONT_KEY_ID: "" # The ID of the AWS CloudFront key used to generate signed photo URLs.
      # GS_PROJECT_ID: ""         # The ID of the GCP project HydroServer is deployed to.
    depends_on:
      hs_postgresql:
        condition: service_started


  hs_nodejs:
    environment:
      VITE_APP_PROXY_BASE_URL: "" # must be set to empty string
    restart: unless-stopped
    container_name: hs_nodejs
    image: node:latest
    working_dir: /app
    ports:
      - 5173:5173
    volumes:
      - ./stack/hydroserver-data-management-app:/app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run docker-dev

  hs_nginx:
    restart: unless-stopped
    container_name: hs_nginx
    image: nginx:latest
    links:
      - hs_nodejs
      - hs_django
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/staticfiles
      - mediafiles:/mediafiles
    ports:
      - "8080:8080"
    depends_on:
      hs_django: 
        condition: service_started
      hs_nodejs: 
        condition: service_started
volumes:
  hydroserver_dev_data:
  staticfiles:
  mediafiles:
